using InventoryManagement.Api.Data;
using InventoryManagement.Api.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagement.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class StockTransactionsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public StockTransactionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // =========================================================
        // GET: api/StockTransactions
        // ADMIN + STAFF
        // =========================================================
        [HttpGet]
        public async Task<IActionResult> GetTransactions()
        {
            var transactions = await _context.StockTransactions
                .Include(t => t.Equipment)
                .Include(t => t.User)
                .OrderByDescending(t => t.TransactionDate)
                .ToListAsync();

            return Ok(transactions);
        }

        // =========================================================
        // GET: api/StockTransactions/{id}
        // ADMIN + STAFF
        // =========================================================
        [HttpGet("{id}")]
        public async Task<IActionResult> GetTransaction(int id)
        {
            var transaction = await _context.StockTransactions
                .Include(t => t.Equipment)
                .Include(t => t.User)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (transaction == null)
            {
                return NotFound(new
                {
                    message = "Stock transaction not found."
                });
            }

            return Ok(transaction);
        }

        // =========================================================
        // POST: api/StockTransactions
        // ADMIN ONLY
        // =========================================================
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateTransaction(
            StockTransaction transaction)
        {
            // Validate transaction type
            if (string.IsNullOrWhiteSpace(transaction.TransactionType))
            {
                return BadRequest(new
                {
                    message = "Transaction type is required. Use IN or OUT."
                });
            }

            transaction.TransactionType =
                transaction.TransactionType.Trim().ToUpper();

            if (transaction.TransactionType != "IN" &&
                transaction.TransactionType != "OUT")
            {
                return BadRequest(new
                {
                    message = "Transaction type must be IN or OUT."
                });
            }

            // Validate quantity
            if (transaction.Quantity <= 0)
            {
                return BadRequest(new
                {
                    message = "Quantity must be greater than zero."
                });
            }

            // Check equipment
            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(e => e.Id == transaction.EquipmentId);

            if (equipment == null)
            {
                return BadRequest(new
                {
                    message = "Selected equipment does not exist."
                });
            }

            // Update stock quantity
            if (transaction.TransactionType == "OUT")
            {
                // Cannot issue more than available stock
                if (transaction.Quantity > equipment.Quantity)
                {
                    return BadRequest(new
                    {
                        message = "Insufficient stock."
                    });
                }

                equipment.Quantity -= transaction.Quantity;
            }
            else // IN
            {
                equipment.Quantity += transaction.Quantity;
            }

            // Set transaction date
            if (transaction.TransactionDate == default)
            {
                transaction.TransactionDate = DateTime.UtcNow;
            }
            else
            {
                transaction.TransactionDate =
                    DateTime.SpecifyKind(
                        transaction.TransactionDate,
                        DateTimeKind.Utc);
            }

            // Make sure ID is generated by database
            transaction.Id = 0;

            // Add transaction
            _context.StockTransactions.Add(transaction);

            // Save equipment quantity + transaction
            await _context.SaveChangesAsync();

            return CreatedAtAction(
                nameof(GetTransaction),
                new { id = transaction.Id },
                transaction
            );
        }

        // =========================================================
        // DELETE: api/StockTransactions/{id}
        // ADMIN ONLY
        // =========================================================
        [HttpDelete("{id}")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteTransaction(int id)
        {
            var transaction = await _context.StockTransactions
                .FirstOrDefaultAsync(t => t.Id == id);

            if (transaction == null)
            {
                return NotFound(new
                {
                    message = "Stock transaction not found."
                });
            }

            // Find related equipment
            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(e => e.Id == transaction.EquipmentId);

            if (equipment != null)
            {
                // Reverse the original transaction

                if (transaction.TransactionType == "IN")
                {
                    // Removing an IN transaction means
                    // removing that quantity from stock

                    if (equipment.Quantity < transaction.Quantity)
                    {
                        return BadRequest(new
                        {
                            message =
                                "Cannot reverse this transaction because current stock is insufficient."
                        });
                    }

                    equipment.Quantity -= transaction.Quantity;
                }
                else if (transaction.TransactionType == "OUT")
                {
                    // Removing an OUT transaction means
                    // returning that quantity to stock

                    equipment.Quantity += transaction.Quantity;
                }
            }

            _context.StockTransactions.Remove(transaction);

            await _context.SaveChangesAsync();

            return Ok(new
            {
                message = "Stock transaction deleted successfully."
            });
        }
    }
}